name: Regenerate Staging Tiles

on:
  workflow_dispatch:
  schedule:
    # Every Monday at 0:00 AM UTC
    # - cron: "0 0 * * 1"
    # Every day at 0:00 AM UTC
    - cron: '0 0 * * *'
jobs:
  generate-tiles:
    uses: ./.github/workflows/generate-tiles.yml
    with:
      ENVIRONMENT: staging
      url: https://staging-tiles.tilda-geo.de
      PROCESSING_DIFFING_MODE: reference
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
