name: Regenerate Production Tiles

on:
  workflow_dispatch:
  schedule:
    # Every day at 0:00 AM UTC
    - cron: '0 0 * * *'
jobs:
  generate-tiles:
    uses: ./.github/workflows/generate-tiles.yml
    with:
      ENVIRONMENT: production
      url: https://tiles.tilda-geo.de
      PROCESSING_DIFFING_MODE: off
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
